### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by moonglum** [rosmo/sails-arangodb#4]
I created a recipe for the [ArangoDB cookbook](https://docs.arangodb.com/cookbook/) on how to use Sails.js with ArangoDB, you can find it [here](https://github.com/arangodb/Cookbook/pull/22). This will however only work, if you publish the package to NPM :smile: Can you maybe do that as a 0.0.1? Or as a pre-release? I know that the test suite is not passing yet, but I think it's a good way to let people try it out and give you feedback!

**Comment by rosmo** [comment]
@moonglum, NPM pushed to: https://www.npmjs.com/package/sails-arangodb

**Comment by moonglum** [comment]
Thanks!
