### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by hannupekka** [rosmo/sails-arangodb#9]
`npm install` installs old version. Could you update it? :)

**Comment by gabriel-letarte** [comment]
It will be done soon :)
I am working on upgrading to using ArangoJS 4.2.0+, when it will be stable enough, I will update the NPM.

**Comment by gabriel-letarte** [comment]
The NPM module has been updated to `0.2.0`
https://www.npmjs.com/package/sails-arangodb
